CREATE DATABASE UserRegistrationDB;
GO

USE UserRegistrationDB;
GO

CREATE TABLE IF NOT EXISTS Users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    RegistrationDate TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    IsActive INTEGER NOT NULL DEFAULT 1
);
GO
